### ISSUE TITLE
network does not support ENS

### ISSUE THREAD

**Issue by Titan-Node** [Eoracle/Eoracle-operator-setup#10]
Getting this error when running `docker compose up -d `  for `data-validator`

```
Starting data-validator
<1> 2024-04-26T19:11:14.739Z info:      Retriveing Eoracle configuration from EOConfig contract
/snapshot/eoracle/node_modules/ethers/lib.commonjs/utils/errors.js:129
            error = new Error(message);
                    ^

Error: network does not support ENS (operation="getEnsAddress", info={ "network": { "chainId": "42420", "name": "unknown" } }, code=UNSUPPORTED_OPERATION, version=6.11.1)
    at makeError (/snapshot/eoracle/node_modules/ethers/lib.commonjs/utils/errors.js:129:21)
    at assert (/snapshot/eoracle/node_modules/ethers/lib.commonjs/utils/errors.js:149:15)
    at EnsResolver.getEnsAddress (/snapshot/eoracle/node_modules/ethers/lib.commonjs/providers/ens-resolver.js:444:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #getResolver (/snapshot/eoracle/node_modules/ethers/lib.commonjs/providers/ens-resolver.js:450:25)
    at async EnsResolver.fromName (/snapshot/eoracle/node_modules/ethers/lib.commonjs/providers/ens-resolver.js:486:26)
    at async JsonRpcProvider.getResolver (/snapshot/eoracle/node_modules/ethers/lib.commonjs/providers/abstract-provider.js:832:16)
    at async JsonRpcProvider.resolveName (/snapshot/eoracle/node_modules/ethers/lib.commonjs/providers/abstract-provider.js:842:26)
    at async checkAddress (/snapshot/eoracle/node_modules/ethers/lib.commonjs/address/checks.js:59:20)
    at async /snapshot/eoracle/node_modules/ethers/lib.commonjs/providers/abstract-provider.js:520:67 {
  code: 'UNSUPPORTED_OPERATION',
  operation: 'getEnsAddress',
  info: { network: Network {} },
  shortMessage: 'network does not support ENS'
}

Node.js v18.5.0
```

I do have an ENS registered to my AVS, could that be the issue?

**Comment by RonTuretzky** [comment]
This is due to a misconfiguration in your .env , I believe we resolved this in the discord? @Titan-Node

**Comment by Titan-Node** [comment]
@RonTuretzky apparently mainnet is not active yet so maybe that is the issue. Will wait until mainnet launch to see if it resolves.

**Comment by RonTuretzky** [comment]
Closing issue
